use_frameworks!

# platform :ios, '8.0'

target 'iOSDemo' do
 pod 'Snowflake', path: '../../'
 pod 'Reindeer', git: 'https://github.com/onmyway133/Reindeer.git'
end


target 'macOSDemo' do
    pod 'Snowflake', path: '../../'
    pod 'Reindeer', git: 'https://github.com/onmyway133/Reindeer.git'
end

